DROP TABLE IF EXISTS operaciones;

CREATE TABLE operaciones (
    id SERIAL PRIMARY KEY,
    num1 DOUBLE PRECISION NOT NULL,
    num2 DOUBLE PRECISION NOT NULL,
    porcentaje_aplicado DOUBLE PRECISION NOT NULL,
    usando_cache BOOLEAN NOT NULL,
    resultado DOUBLE PRECISION NOT NULL,
    fecha TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);